/* Lara Fire – Firebase Cloud Messaging service worker (generated by Laravel) */
importScripts('https://www.gstatic.com/firebasejs/12.19.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/12.19.0/firebase-messaging-compat.js');

const config = @json((object) $config);

if (config.apiKey && config.messagingSenderId) {
    firebase.initializeApp(config);
    // Messages with a `notification` payload are displayed automatically by the SDK.
    firebase.messaging();
}
